# =============================================================================
# Solt Pre-commit Hooks
# Available hooks for consumption from Odoo module repositories
# =============================================================================

# -----------------------------------------------------------------------------
# BRANCH NAME - Branch naming policy validation
# -----------------------------------------------------------------------------
- id: solt-check-branch
  name: Soltein - Validate Branch Name
  description: |
    Validate branch naming convention.
    Configure in .solt-hooks.yaml:
    - strict: true  → Requires ticket (feature/SOLT-123-desc)
    - strict: false → Type/description only (feature/my-change)
  entry: solt-check-branch
  language: python
  always_run: true
  pass_filenames: false
  stages: [ pre-commit, pre-push ]

# -----------------------------------------------------------------------------
# FULL VALIDATION - All checks (XML, CSV, PO, Python, Manifest)
# -----------------------------------------------------------------------------
# This hook now automatically detects Odoo modules from individual files
# passed by pre-commit. No configuration needed.
# -----------------------------------------------------------------------------
- id: solt-check-odoo
  name: Soltein - Validate Odoo Module
  description: |
    Run all validations on Odoo modules.
    Automatically detects modules from staged files.
    Respects validation_scope in .solt-hooks.yaml:
    - "changed": Only validate files changed in PR/commit
    - "full": Validate entire repository
  entry: solt-check-odoo
  language: python
  # Match any file that could be part of an Odoo module
  files: (__manifest__|__openerp__|\.py|\.xml|\.csv|\.po|\.pot)$
  # Pass filenames so the hook can detect which modules to validate
  pass_filenames: true
  # Show output
  verbose: true

# -----------------------------------------------------------------------------
# XML ONLY - Basic and advanced XML validations
# -----------------------------------------------------------------------------
- id: solt-check-xml
  name: Soltein - Validate Odoo XML
  description: Validate XML files (syntax, duplicates, deprecations, etc.)
  entry: solt-check-odoo
  language: python
  files: \.xml$
  pass_filenames: true
  args: [ --check-xml-only ]
  verbose: true

# -----------------------------------------------------------------------------
# CSV ONLY - CSV data file validations
# -----------------------------------------------------------------------------
- id: solt-check-csv
  name: Soltein - Validate Odoo CSV
  description: Validate CSV files (syntax, duplicate IDs)
  entry: solt-check-odoo
  language: python
  files: \.csv$
  pass_filenames: true
  args: [ --check-csv-only ]
  verbose: true

# -----------------------------------------------------------------------------
# PO/POT ONLY - Translation file validations
# -----------------------------------------------------------------------------
- id: solt-check-po
  name: Soltein - Validate Odoo PO/POT
  description: Validate translation files (syntax, duplicates, variables)
  entry: solt-check-odoo
  language: python
  files: \.(po|pot)$
  pass_filenames: true
  args: [ --check-po-only ]
  verbose: true

# -----------------------------------------------------------------------------
# PYTHON ONLY - Python code validations
# -----------------------------------------------------------------------------
- id: solt-check-python
  name: Soltein - Validate Odoo Python
  description: |
    Validate Python files:
    - Fields: string, help attributes
    - Docstrings: presence and quality
    - Runtime warnings: tracking, compute_sudo, etc.
  entry: solt-check-odoo
  language: python
  files: \.py$
  pass_filenames: true
  args: [ --check-python-only ]
  verbose: true
