# -*- coding: utf-8 -*-
# Copyright 2026 Soltein SA. de CV.
# License LGPL-3 or later (http://www.gnu.org/licenses/lgpl.html)

"""Tests for checks_requirements.py: normalizing/deduping manifestoo's raw
external-dependencies output, comparing it against an existing
requirements.txt, and the `solt-check-requirements` CLI entry point (check
mode and --fix mode), including the subprocess boundary with git/manifestoo."""

import subprocess
import sys
from unittest import mock

import pytest

from solt_pre_commit.checks_requirements import (
    RequirementsConflictError,
    main,
    normalize,
    parse_requirement_set,
    render,
)


class TestNormalize:
    def test_dedupes_identical_declarations(self):
        assert normalize(["requests", "requests"]) == ["requests"]

    def test_sorts_case_insensitively(self):
        assert normalize(["numpy", "Jinja2", "boto3"]) == ["boto3", "Jinja2", "numpy"]

    def test_prefers_the_specifier_over_the_bare_name(self):
        # llm_knowledge declares "pydantic", llm_tool declares "pydantic>=2.0.0" -
        # the specifier is strictly more informative, keep it.
        assert normalize(["pydantic", "pydantic>=2.0.0"]) == ["pydantic>=2.0.0"]
        assert normalize(["pydantic>=2.0.0", "pydantic"]) == ["pydantic>=2.0.0"]

    def test_non_pep508_entries_kept_verbatim(self):
        # manifestoo can list bare tool/binary-ish names that aren't valid
        # PEP 508 requirements on their own.
        assert normalize(["sqlparse", "not a valid==req=="]) == sorted(
            ["sqlparse", "not a valid==req=="], key=str.lower
        )

    def test_conflicting_specifiers_raise(self):
        with pytest.raises(RequirementsConflictError) as exc_info:
            normalize(["paramiko<4.0.0", "paramiko>=2.0.0"])
        (name, a, b) = exc_info.value.conflicts[0]
        assert name == "paramiko"
        assert {a, b} == {"paramiko<4.0.0", "paramiko>=2.0.0"}

    def test_underscore_and_dash_names_are_the_same_package(self):
        assert normalize(["odoo_test_helper", "odoo-test-helper"]) == ["odoo_test_helper"]

    def test_empty_input_returns_empty(self):
        assert normalize([]) == []


class TestRenderAndParseRoundtrip:
    def test_render_then_parse_matches_normalized_input(self):
        lines = normalize(["requests", "pgvector", "numpy"])
        content = render(lines)
        assert parse_requirement_set(content) == parse_requirement_set("\n".join(lines))

    def test_render_of_empty_list_is_header_only(self):
        content = render([])
        assert parse_requirement_set(content) == set()

    def test_parse_ignores_comments_and_blank_lines(self):
        text = "# a comment\n\nrequests\n\n# another\nnumpy==2.2.6\n"
        assert parse_requirement_set(text) == {"requests", "numpy==2.2.6"}

    def test_parse_is_order_and_header_independent(self):
        a = "# generated from manifests external_dependencies\nsqlparse\nrequests\n"
        b = "# Generated by solt-check-requirements ...\nrequests\nsqlparse\n"
        assert parse_requirement_set(a) == parse_requirement_set(b)

    def test_parse_normalizes_case_and_separators(self):
        assert parse_requirement_set("odoo_test_helper\n") == parse_requirement_set("Odoo-Test-Helper\n")


class TestMainCli:
    def _run(self, argv, monkeypatch, *, git_ok=True, git_root="/repo", manifestoo_stdout="requests\n"):
        monkeypatch.setattr(sys, "argv", ["solt-check-requirements", *argv])

        def fake_run(cmd, **kwargs):
            if cmd[:2] == ["git", "-C"] or (len(cmd) > 1 and cmd[0] == "git"):
                if not git_ok:
                    raise subprocess.CalledProcessError(1, cmd)
                return mock.Mock(stdout=f"{git_root}\n", returncode=0)
            if cmd[0] == "manifestoo":
                return mock.Mock(stdout=manifestoo_stdout, stderr="", returncode=0)
            raise AssertionError(f"unexpected command: {cmd}")

        with mock.patch("subprocess.run", side_effect=fake_run):
            with pytest.raises(SystemExit) as exc_info:
                main()
        return exc_info.value.code

    def test_not_a_git_repo_exits_one(self, monkeypatch, capsys):
        code = self._run([], monkeypatch, git_ok=False)
        assert code == 1
        assert "not inside a git repository" in capsys.readouterr().err

    def test_in_sync_repo_exits_zero(self, tmp_path, monkeypatch):
        (tmp_path / "requirements.txt").write_text("requests\n")
        code = self._run(["--path", str(tmp_path)], monkeypatch, git_root=str(tmp_path))
        assert code == 0

    def test_missing_file_without_fix_exits_one(self, tmp_path, monkeypatch, capsys):
        code = self._run(["--path", str(tmp_path)], monkeypatch, git_root=str(tmp_path))
        assert code == 1
        assert "out of sync" in capsys.readouterr().err
        assert not (tmp_path / "requirements.txt").exists()

    def test_fix_writes_the_file(self, tmp_path, monkeypatch, capsys):
        code = self._run(["--path", str(tmp_path), "--fix"], monkeypatch, git_root=str(tmp_path))
        assert code == 0
        content = (tmp_path / "requirements.txt").read_text()
        assert "requests" in content
        assert "Updated" in capsys.readouterr().out

    def test_stale_content_is_fixed_in_place(self, tmp_path, monkeypatch):
        (tmp_path / "requirements.txt").write_text("old-unused-package\n")
        code = self._run(["--path", str(tmp_path), "--fix"], monkeypatch, git_root=str(tmp_path))
        assert code == 0
        content = (tmp_path / "requirements.txt").read_text()
        assert "old-unused-package" not in content
        assert "requests" in content

    def test_conflicting_manifests_exit_one_and_do_not_touch_the_file(self, tmp_path, monkeypatch, capsys):
        (tmp_path / "requirements.txt").write_text("paramiko<4.0.0\n")
        code = self._run(
            ["--path", str(tmp_path), "--fix"],
            monkeypatch,
            git_root=str(tmp_path),
            manifestoo_stdout="paramiko<4.0.0\nparamiko>=2.0.0\n",
        )
        assert code == 1
        assert "Conflicting external_dependencies" in capsys.readouterr().err
        assert (tmp_path / "requirements.txt").read_text() == "paramiko<4.0.0\n"

    def test_manifestoo_not_installed_exits_one(self, monkeypatch, capsys):
        monkeypatch.setattr(sys, "argv", ["solt-check-requirements"])

        def fake_run(cmd, **kwargs):
            if cmd[0] == "manifestoo":
                raise FileNotFoundError()
            return mock.Mock(stdout="/repo\n", returncode=0)

        with mock.patch("subprocess.run", side_effect=fake_run):
            with pytest.raises(SystemExit) as exc_info:
                main()
        assert exc_info.value.code == 1
        assert "manifestoo not found" in capsys.readouterr().err


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
