# =============================================================================
# SOLT VALIDATION + WEEKLY BADGES
# =============================================================================
# This workflow runs:
# 1. Validation on every PR/push (solt-validate.yml)
# 2. Badge updates weekly (solt-update-badges.yml)
#
# CENTRALIZED BADGES:
# - All badges stored in Soltein's Central Gist
# - No configuration needed - uses repository name automatically
# =============================================================================
name: Solt Validation

on:
  push:
    branches:
      - main
      - master
      - develop
      - '17.0'
      - '18.0'
      - '19.0'
      - '*.0'
  pull_request:
    branches:
      - main
      - master
      - develop
      - '17.0'
      - '18.0'
      - '19.0'
      - '*.0'

  # Weekly badge updates - Every Monday at 6:00 AM UTC
  schedule:
    - cron: '0 6 * * 1'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------
  # PR/PUSH VALIDATION
  # ---------------------------------------------------------------------------
  validate:
    if: github.event_name != 'schedule'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-validate.yml@v1.0.0
    with:
      validation-scope: 'changed'
      fail-on-warnings: true
      pylint-blocking: true
      ruff-blocking: false
      docstring-threshold: 80

  # ---------------------------------------------------------------------------
  # WEEKLY BADGE UPDATES
  # ---------------------------------------------------------------------------
  update-badges:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-update-badges.yml@v1.0.0
    # No inputs needed - uses defaults:
    # - gist-id: Soltein central gist (147d543a086f6735d1ffa02172766e86)
    # - badge-filename-prefix: repository name (automatic)
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
