# =============================================================================
# SOLT PRE-COMMIT - Client Repository Workflow
# =============================================================================
# This workflow runs validation ONLY on Pull Requests
# Once a PR is merged, validation is not re-run (already validated in PR)
#
# SETUP:
# 1. Copy this file to .github/workflows/solt-validate.yml
# 2. For badges: Configure GIST_SECRET in repository/organization secrets
# =============================================================================

name: Soltein Validation

on:
  pull_request:
    branches: [ main, master, develop, '17.0', '18.0', '19.0' ]
  # Weekly badge updates
  schedule:
    - cron: '0 6 * * 1'  # Mondays at 6 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------------------------------------------------------------------------
  # VALIDATION - Runs ONLY on Pull Requests
  # ---------------------------------------------------------------------------
  validate:
    if: github.event_name == 'pull_request'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-validate.yml@v1.0.1
    with:
      validation-scope: 'changed'
      fail-on-warnings: true
      pylint-blocking: true
      ruff-blocking: false
      show-info: false

  # ---------------------------------------------------------------------------
  # WEEKLY BADGE UPDATES
  # ---------------------------------------------------------------------------
  Update-Badges:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-update-badges.yml@v1.0.1
    with:
      gist-id: ${{ vars.SOLTEIN_GIST_ID }}
      badge-filename-prefix: ${{ github.event.repository.name }}
      docstring-threshold: 80
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
