# =============================================================================
# SOLT PRE-COMMIT - Client Repository Workflow
# =============================================================================
# This workflow runs validation on PRs and pushes
# Badge updates run weekly (optional - requires GIST_SECRET)
#
# SETUP:
# 1. Copy this file to .github/workflows/solt-validate.yml
# 2. For badges: Configure GIST_SECRET in repository/organization secrets
# =============================================================================

name: Soltein Validation

on:
  push:
    branches: [ main, master, develop, '17.0', '18.0', '19.0' ]
  pull_request:
    branches: [ main, master, develop, '17.0', '18.0', '19.0' ]
  # Weekly badge updates - uncomment schedule to enable
  schedule:
    - cron: '0 6 * * 1'  # Mondays at 6 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------------------------------------------------------------------------
  # VALIDATION - Runs on PRs and pushes
  # ---------------------------------------------------------------------------
  Validate:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-validate.yml@v1.0.1
    with:
      validation-scope: 'changed'
      fail-on-warnings: true
      pylint-blocking: true
      ruff-blocking: false
      show-info: false

  # ---------------------------------------------------------------------------
  # WEEKLY BADGE UPDATES
  # ---------------------------------------------------------------------------
  Update-Badges:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-update-badges.yml@v1.0.1
    with:
      gist-id: ${{ vars.SOLTEIN_GIST_ID }}
      badge-filename-prefix: ${{ github.event.repository.name }}
      docstring-threshold: 80
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
