# =============================================================================
# SOLT PRE-COMMIT HOOKS - Configuration
# =============================================================================
# Place this file in your repository root
# =============================================================================

# =============================================================================
# VALIDATION SCOPE
# =============================================================================
# Controls which files are validated:
#   - "changed": Only validate files changed in PR/commit (recommended for legacy)
#   - "full": Validate entire repository (for clean repos)

validation_scope: changed

# Base branch for detecting changed files (auto-detected if not set)
# base_branch: main

# =============================================================================
# BRANCH NAMING POLICY
# =============================================================================
# Supports Odoo multi-version branch patterns:
#   - Direct version: 17.0, 18.0 (protected)
#   - Version-prefixed: feature/17.0-description, hotfix/18.0-fix
#   - Standard: feature/description, fix/TICKET-123-description
#   - Release: release/17.0.1.0
# =============================================================================
branch_naming:
  strict: false  # true = requires ticket OR version (feature/SOLT-123-desc OR feature/17.0-desc)

  # Ticket prefixes (used when strict: true)
  ticket_prefixes:
    - SOLT
    - PROJ

  # Allowed branch types with pattern: <type>/<description>
  # All types support version prefix: <type>/<odoo-version>-<description>
  allowed_types:
    - feature    # feature/add-invoice OR feature/17.0-add-invoice
    - fix        # fix/bug-name OR fix/18.0-critical-fix
    - hotfix     # hotfix/urgent OR hotfix/17.0-urgent
    - bugfix
    - release    # release/17.0.1.0
    - refactor
    - docs
    - test
    - chore

  # Protected branches (skip validation entirely)
  protected_branches:
    - main
    - master
    - develop
    - staging
    - production

  # Protected patterns (regex) - branches matching these skip validation
  # Odoo version branches are protected by default
  protected_patterns:
    # Direct version branches (17.0, 18.0, etc.)
    - "^\\d+\\.0$"
    # Version with patch (17.0.1.0, 17.0-stable, etc.)
    - "^\\d+\\.0\\.\\d+.*$"
    # Custom patterns (add your own)
    # - "^feature/17\\.0-.*$"  # Uncomment to also protect feature branches

# =============================================================================
# DISABLED CHECKS
# =============================================================================
# Completely disable specific checks
disabled_checks: [ ]
  # - missing_readme
# - po_requires_module

# =============================================================================
# SEVERITY LEVELS
# =============================================================================
# Override default severities: error, warning, info
severity:
  # Code quality - adjust as needed
  python_field_missing_string: warning
  python_field_missing_help: warning
  python_method_missing_docstring: warning
  python_docstring_too_short: info
  python_docstring_uninformative: info

# =============================================================================
# BLOCKING SEVERITIES
# =============================================================================
blocking_severities:
  - error
  - warning

# =============================================================================
# SKIP LISTS
# =============================================================================
skip_string_fields:
  - active
  - name
  - display_name
  - sequence
  - company_id
  - currency_id
  - create_uid
  - create_date
  - write_uid
  - write_date
  - message_ids
  - message_follower_ids
  - activity_ids

skip_help_fields:
  - active
  - name
  - display_name
  - sequence
  - company_id
  - currency_id
  - create_uid
  - create_date
  - write_uid
  - write_date
  - message_ids
  - message_follower_ids
  - activity_ids
  - state

skip_docstring_methods: [ ]
  # - default_get
  # - create
  # - write
# - unlink

min_docstring_length: 10

# =============================================================================
# PATH EXCLUSIONS
# =============================================================================
exclude_paths:
  - "**/migrations/**"
  - "**/tests/**"
  - "**/static/**"
  - "**/__pycache__/**"
  - "**/node_modules/**"
