#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2025 Soltein SA. de CV.
# License LGPL-3 or later (http://www.gnu.org/licenses/lgpl.html)

"""Setup script to initialize solt-pre-commit in a client repository.

Usage:
    python setup-repo.py /path/to/odoo-repo
    python setup-repo.py /path/to/odoo-repo --gist-id abc123
    python setup-repo.py /path/to/odoo-repo --dry-run
    python setup-repo.py /path/to/odoo-repo --local  # For monorepo

Example:
    python scripts/setup-repo.py ../solt-budget --gist-id d5c6f3e13a63278457b6323ae9db098e
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# PATH CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent.absolute()
REPO_ROOT = SCRIPT_DIR.parent
TEMPLATES_DIR = REPO_ROOT / "templates"
CONFIGS_DIR = REPO_ROOT / "configs"

# ─────────────────────────────────────────────────────────────────────────────
# FILE MAPPINGS
# ─────────────────────────────────────────────────────────────────────────────
FILES_TO_COPY = [
    (CONFIGS_DIR / ".pylintrc", ".pylintrc", "Pylint configuration"),
    (CONFIGS_DIR / "pyproject-base.toml", "pyproject.toml", "Python project configuration"),
    (TEMPLATES_DIR / ".solt-hooks.yaml", ".solt-hooks.yaml", "Solt hooks configuration"),
]

PRECOMMIT_REMOTE = (
    TEMPLATES_DIR / ".pre-commit-config.yaml",
    ".pre-commit-config.yaml",
    "Pre-commit config (GitHub)",
)
PRECOMMIT_LOCAL = (
    TEMPLATES_DIR / ".pre-commit-config-local.yaml",
    ".pre-commit-config.yaml",
    "Pre-commit config (local/monorepo)",
)

# ─────────────────────────────────────────────────────────────────────────────
# WORKFLOW TEMPLATE
# ─────────────────────────────────────────────────────────────────────────────
WORKFLOW_TEMPLATE = """# =============================================================================
# VALIDATION WORKFLOW
# =============================================================================
# Generated by: solt-pre-commit setup-repo.py
#
# - PR validation: Runs on every pull request (fast, changed files only)
# - Badge update: Runs weekly on Sundays at 00:00 UTC
# =============================================================================

name: Validate

on:
  pull_request:
    branches: [ main, master, develop, "17.0", "18.0" ]

  # Weekly badge update (Sundays at 00:00 UTC)
  schedule:
    - cron: '0 0 * * 0'

  # Allow manual trigger for badge update
  workflow_dispatch:

jobs:
  # ---------------------------------------------------------------------------
  # PR VALIDATION (only on pull_request)
  # ---------------------------------------------------------------------------
  validate:
    if: github.event_name == 'pull_request'
    name: Soltein Validation
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-validate.yml@v1.0.0
    with:
      python-version: '3.11'
      fail-on-warnings: {fail_on_warnings}
      pylint-blocking: {pylint_blocking}
      ruff-blocking: {ruff_blocking}

  # ---------------------------------------------------------------------------
  # WEEKLY BADGE UPDATE (schedule or manual)
  # ---------------------------------------------------------------------------
  update-badges:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    name: Update Badges
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-update-badges.yml@v1.0.0
    with:
      python-version: '3.11'
      gist-id: '{gist_id}'
      badge-filename-prefix: '{badge_prefix}'
      docstring-threshold: {docstring_threshold}
      branch: '{default_branch}'
    secrets:
      GIST_SECRET: ${{{{ secrets.GIST_SECRET }}}}
"""

WORKFLOW_TEMPLATE_NO_BADGES = """# =============================================================================
# VALIDATION WORKFLOW
# =============================================================================
# Generated by: solt-pre-commit setup-repo.py
#
# - PR validation: Runs on every pull request (fast, changed files only)
# =============================================================================

name: Validate

on:
  pull_request:
    branches: [ main, master, develop, "17.0", "18.0" ]

jobs:
  validate:
    name: Soltein Validation
    uses: soltein-net/solt-pre-commit/.github/workflows/solt-validate.yml@v1.0.0
    with:
      python-version: '3.11'
      fail-on-warnings: {fail_on_warnings}
      pylint-blocking: {pylint_blocking}
      ruff-blocking: {ruff_blocking}
"""


def print_header(text: str) -> None:
    """Print a formatted header."""
    print(f"\n{'─' * 60}")
    print(f"  {text}")
    print(f"{'─' * 60}")


def print_step(icon: str, text: str) -> None:
    """Print a step with icon."""
    print(f"  {icon} {text}")


def copy_file(src: Path, dest: Path, dry_run: bool = False, force: bool = True) -> bool:
    """Copy a file to destination, creating directories as needed."""
    if not src.exists():
        print_step("⚠️ ", f"Source not found: {src}")
        return False

    if dest.exists() and not force:
        print_step("⏭️ ", f"Skipped (exists): {dest.name}")
        return False

    action = "overwrite" if dest.exists() else "create"

    if dry_run:
        print_step("📄", f"Would {action}: {dest}")
        return True

    try:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        icon = "🔄" if action == "overwrite" else "✅"
        print_step(icon, f"{'Updated' if action == 'overwrite' else 'Created'}: {dest}")
        return dest.exists()
    except Exception as e:
        print_step("❌", f"Error copying {src.name}: {e}")
        return False


def write_file(dest: Path, content: str, dry_run: bool = False, force: bool = True) -> bool:
    """Write content to a file."""
    if dest.exists() and not force:
        print_step("⏭️ ", f"Skipped (exists): {dest.name}")
        return False

    action = "overwrite" if dest.exists() else "create"

    if dry_run:
        print_step("📄", f"Would {action}: {dest}")
        return True

    try:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
        icon = "🔄" if action == "overwrite" else "✅"
        print_step(icon, f"{'Updated' if action == 'overwrite' else 'Created'}: {dest}")
        return True
    except Exception as e:
        print_step("❌", f"Error writing {dest.name}: {e}")
        return False


def update_file_content(filepath: Path, replacements: dict[str, str], dry_run: bool = False) -> bool:
    """Update file content with replacements."""
    if not filepath.exists():
        return False

    content = filepath.read_text()
    modified = False

    for old, new in replacements.items():
        if old in content:
            content = content.replace(old, new)
            modified = True

    if modified and not dry_run:
        filepath.write_text(content)
        print_step("✏️ ", f"Updated: {filepath.name}")

    return modified


def install_precommit_hooks(target: Path, dry_run: bool = False) -> bool:
    """Install pre-commit hooks in target repository."""
    if dry_run:
        print_step("📄", "Would run: pre-commit install")
        return True

    try:
        subprocess.run(["pre-commit", "install"], cwd=target, check=True, capture_output=True)
        print_step("✅", "Pre-commit hooks installed")
        return True
    except subprocess.CalledProcessError as e:
        print_step("⚠️ ", f"Failed to install hooks: {e}")
        return False
    except FileNotFoundError:
        print_step("⚠️ ", "pre-commit not found. Install with: pip install pre-commit")
        return False


def cleanup_old_files(target: Path, dry_run: bool = False) -> None:
    """Remove old config files that are now consolidated."""
    old_files = ["ruff.toml"]

    for filename in old_files:
        filepath = target / filename
        if filepath.exists():
            if dry_run:
                print_step("🗑️ ", f"Would remove: {filename}")
            else:
                filepath.unlink()
                print_step("🗑️ ", f"Removed: {filename}")


def detect_default_branch(target: Path) -> str:
    """Detect the default branch of the repository."""
    try:
        result = subprocess.run(
            ["git", "symbolic-ref", "refs/remotes/origin/HEAD"],
            cwd=target,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            # refs/remotes/origin/main -> main
            return result.stdout.strip().split("/")[-1]
    except Exception:
        pass

    # Check common branches
    for branch in ["main", "master", "17.0", "18.0", "develop"]:
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--verify", f"origin/{branch}"],
                cwd=target,
                capture_output=True,
            )
            if result.returncode == 0:
                return branch
        except Exception:
            pass

    return "main"


def setup_repo(
    target_path: str,
    gist_id: str | None = None,
    dry_run: bool = False,
    local: bool = False,
    force: bool = True,
    fail_on_warnings: bool = True,
    pylint_blocking: bool = True,
    ruff_blocking: bool = False,
    docstring_threshold: int = 80,
) -> None:
    """Setup solt-pre-commit in a target repository."""
    target = Path(target_path).absolute()

    if not target.exists():
        print(f"❌ Target path does not exist: {target}")
        sys.exit(1)

    repo_name = target.name
    default_branch = detect_default_branch(target)

    # ─────────────────────────────────────────────────────────────────────
    # HEADER
    # ─────────────────────────────────────────────────────────────────────
    mode_str = "DRY RUN - " if dry_run else ""
    print(f"\n{'=' * 60}")
    print(f"🚀 {mode_str}Setting up solt-pre-commit")
    print(f"{'=' * 60}")
    print(f"  Target:         {target}")
    print(f"  Repository:     {repo_name}")
    print(f"  Default branch: {default_branch}")
    print(f"  Mode:           {'local (monorepo)' if local else 'remote (GitHub)'}")
    print(f"  Gist ID:        {gist_id or '(none - badges disabled)'}")
    print(f"{'=' * 60}")

    # ─────────────────────────────────────────────────────────────────────
    # CLEANUP OLD FILES
    # ─────────────────────────────────────────────────────────────────────
    print_header("🧹 Cleanup Old Files")
    cleanup_old_files(target, dry_run)

    # ─────────────────────────────────────────────────────────────────────
    # COPY CONFIG FILES
    # ─────────────────────────────────────────────────────────────────────
    print_header("📁 Configuration Files")

    files = FILES_TO_COPY.copy()
    files.append(PRECOMMIT_LOCAL if local else PRECOMMIT_REMOTE)

    copied = 0
    for src, dest_rel, description in files:
        dest = target / dest_rel
        print(f"\n  [{description}]")
        if src.exists() and copy_file(src, dest, dry_run, force):
            copied += 1

    # ─────────────────────────────────────────────────────────────────────
    # GENERATE WORKFLOW FILE
    # ─────────────────────────────────────────────────────────────────────
    print_header("📁 GitHub Workflow")

    workflow_dest = target / ".github" / "workflows" / "solt-validate.yml"

    if gist_id:
        workflow_content = WORKFLOW_TEMPLATE.format(
            fail_on_warnings=str(fail_on_warnings).lower(),
            pylint_blocking=str(pylint_blocking).lower(),
            ruff_blocking=str(ruff_blocking).lower(),
            gist_id=gist_id,
            badge_prefix=repo_name,
            docstring_threshold=docstring_threshold,
            default_branch=default_branch,
        )
    else:
        workflow_content = WORKFLOW_TEMPLATE_NO_BADGES.format(
            fail_on_warnings=str(fail_on_warnings).lower(),
            pylint_blocking=str(pylint_blocking).lower(),
            ruff_blocking=str(ruff_blocking).lower(),
        )

    write_file(workflow_dest, workflow_content, dry_run, force)

    # ─────────────────────────────────────────────────────────────────────
    # INSTALL HOOKS
    # ─────────────────────────────────────────────────────────────────────
    print_header("🔧 Installing Hooks")
    install_precommit_hooks(target, dry_run)

    # ─────────────────────────────────────────────────────────────────────
    # SUMMARY
    # ─────────────────────────────────────────────────────────────────────
    print(f"\n{'=' * 60}")
    print("📋 DRY RUN COMPLETE - No changes made" if dry_run else "✅ SETUP COMPLETE")
    print(f"{'=' * 60}")

    print("\n📂 Files created/updated:")
    print("   pyproject.toml                        → Python tools config")
    print("   .pylintrc                             → Pylint-odoo configuration")
    print("   .solt-hooks.yaml                      → Soltein validation settings")
    print("   .pre-commit-config.yaml               → Pre-commit hooks")
    print("   .github/workflows/solt-validate.yml   → CI workflow")

    print("\n⚡ Workflow behavior:")
    print("   • Pull Request  → Validation (changed files only, ~5-10s)")
    if gist_id:
        print("   • Weekly (Sun)  → Badge update (full repo scan)")
        print("   • Manual        → Badge update (workflow_dispatch)")
    else:
        print("   • Badges        → Disabled (no gist-id provided)")

    print("\n📋 Next steps:")
    print("   1. Review .github/workflows/solt-validate.yml")
    if not gist_id:
        print("   2. Add --gist-id to enable weekly badge updates")
    print("   3. Ensure GIST_SECRET is set in repository secrets")
    print("   4. Commit the configuration files")
    print("")


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Setup solt-pre-commit in a client repository",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic setup (no badges)
  python setup-repo.py /path/to/solt-budget

  # Setup with weekly badge updates
  python setup-repo.py /path/to/solt-budget --gist-id d5c6f3e13a63278457b6323ae9db098e

  # Preview changes
  python setup-repo.py /path/to/solt-budget --dry-run

  # Monorepo setup
  python setup-repo.py /path/to/solt-addons --local

  # Custom options
  python setup-repo.py /path/to/repo --gist-id abc123 --docstring-threshold 70
        """,
    )

    parser.add_argument("path", help="Path to the target repository")
    parser.add_argument("--gist-id", default=None, help="Gist ID for badge storage (enables weekly updates)")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without applying")
    parser.add_argument("--local", action="store_true", help="Use local hooks (for monorepo)")
    parser.add_argument("--no-force", action="store_true", help="Don't overwrite existing files")
    parser.add_argument(
        "--fail-on-warnings", action="store_true", default=True, help="Fail on warnings (default: true)"
    )
    parser.add_argument("--no-fail-on-warnings", action="store_true", help="Don't fail on warnings")
    parser.add_argument("--pylint-blocking", action="store_true", default=True, help="Block on pylint (default: true)")
    parser.add_argument("--no-pylint-blocking", action="store_true", help="Don't block on pylint")
    parser.add_argument("--ruff-blocking", action="store_true", default=False, help="Block on ruff (default: false)")
    parser.add_argument(
        "--docstring-threshold", type=int, default=80, help="Docstring coverage threshold (default: 80)"
    )

    args = parser.parse_args()

    setup_repo(
        target_path=args.path,
        gist_id=args.gist_id,
        dry_run=args.dry_run,
        local=args.local,
        force=not args.no_force,
        fail_on_warnings=not args.no_fail_on_warnings,
        pylint_blocking=not args.no_pylint_blocking,
        ruff_blocking=args.ruff_blocking,
        docstring_threshold=args.docstring_threshold,
    )


if __name__ == "__main__":
    main()
