# -*- coding: utf-8 -*-
# Copyright 2026 Soltein SA. de CV.
# License LGPL-3 or later (http://www.gnu.org/licenses/lgpl.html)

"""Verify (or regenerate) a repo's root requirements.txt from its addons.

The single source of truth for an addon's Python dependencies is its own
`__manifest__.py` `external_dependencies["python"]` - that's Odoo's own
module-level declaration, checked by Odoo itself before allowing a module to
install. A hand-maintained root requirements.txt drifts from that the moment
someone edits a manifest and forgets the file; this hook uses manifestoo
(https://github.com/acsone/manifestoo) to read every installable addon's
manifest under the repo and keeps requirements.txt an exact, generated
reflection of them.

A physical per-module requirements.txt file was considered and rejected -
OCA discussed the same idea and dropped it, since it just moves the
duplication one level down instead of removing it:
https://odoo-community.org/groups/contributors-15/contributors-187062
"""

import argparse
import subprocess
import sys
from pathlib import Path

from packaging.requirements import InvalidRequirement, Requirement

HEADER = (
    "# Generated by solt-check-requirements from addon manifests'"
    " external_dependencies.python - do not edit by hand.\n"
    "# Run `solt-check-requirements --fix` after changing a manifest.\n"
)


class RequirementsConflictError(Exception):
    """Two addons in the same repo declare incompatible constraints for the same package."""

    def __init__(self, conflicts):
        self.conflicts = conflicts
        message = "; ".join(f"{name}: {a!r} vs {b!r}" for name, a, b in conflicts)
        super().__init__(message)


def _repo_root(start: Path) -> Path:
    result = subprocess.run(
        ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    return Path(result.stdout.strip())


def _manifestoo_external_dependencies(repo_root: Path) -> list[str]:
    """Raw, one-per-line `python` external_dependencies for every installable
    addon manifestoo finds under repo_root, exactly as declared (not yet
    deduped/normalized - two addons may legitimately declare the same
    package with different specifiers)."""
    result = subprocess.run(
        [
            "manifestoo",
            "-d",
            str(repo_root),
            "--select-found",
            "list-external-dependencies",
            "python",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _canonical_name(name: str) -> str:
    return name.lower().replace("_", "-")


def normalize(raw_lines: list[str]) -> list[str]:
    """Dedupe declarations by canonical package name, sorted for a stable diff.

    Raises RequirementsConflictError if two addons declare different, non-empty
    version specifiers for the same package - that needs a human to resolve,
    not a silent pick.
    """
    by_name: dict[str, str] = {}
    conflicts = []
    for line in raw_lines:
        try:
            req = Requirement(line)
        except InvalidRequirement:
            # Not a real PEP 508 requirement (e.g. a bare binary/tool name
            # manifestoo still listed) - keep it verbatim, keyed on itself.
            by_name.setdefault(line, line)
            continue

        key = _canonical_name(req.name)
        existing = by_name.get(key)
        if existing is None:
            by_name[key] = line
            continue
        if existing == line:
            continue

        existing_req = Requirement(existing)
        if existing_req.specifier == req.specifier:
            pass  # same constraint (including "both bare") - nothing to reconcile
        elif not existing_req.specifier:
            by_name[key] = line  # existing was bare, this one is more informative
        elif not req.specifier:
            pass  # this one is bare, existing already has a specifier - keep it
        else:
            conflicts.append((key, existing, line))

    if conflicts:
        raise RequirementsConflictError(conflicts)

    return sorted(by_name.values(), key=str.lower)


def render(lines: list[str]) -> str:
    body = "\n".join(lines)
    return HEADER + "\n" + body + "\n" if lines else HEADER


def parse_requirement_set(text: str) -> set[str]:
    """Reduce a requirements.txt's content to a comparable set of canonical
    `name<specifier>` entries - ignoring comments, blank lines, and line
    order, so an existing hand-written file with a different header/ordering
    still compares equal when its actual dependencies already match."""
    entries = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            req = Requirement(line)
            entries.add(f"{_canonical_name(req.name)}{req.specifier}")
        except InvalidRequirement:
            entries.add(line.lower())
    return entries


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Regenerate requirements.txt in place instead of just checking it.",
    )
    parser.add_argument(
        "--path",
        default=".",
        help="Directory inside the repo to check (default: cwd). The repo root is "
        "resolved from here via `git rev-parse --show-toplevel`.",
    )
    args = parser.parse_args()

    start = Path(args.path).resolve()
    try:
        repo_root = _repo_root(start)
    except subprocess.CalledProcessError:
        print(f"{start} is not inside a git repository", file=sys.stderr)
        sys.exit(1)

    try:
        raw = _manifestoo_external_dependencies(repo_root)
    except FileNotFoundError:
        print(
            "manifestoo not found - install it (pip install manifestoo) to run this check",
            file=sys.stderr,
        )
        sys.exit(1)
    except subprocess.CalledProcessError as exc:
        print(f"manifestoo failed:\n{exc.stderr}", file=sys.stderr)
        sys.exit(1)

    try:
        lines = normalize(raw)
    except RequirementsConflictError as exc:
        print(
            "Conflicting external_dependencies across addons in this repo - resolve manually:",
            file=sys.stderr,
        )
        for name, a, b in exc.conflicts:
            print(f"  {name}: {a!r} vs {b!r}", file=sys.stderr)
        sys.exit(1)

    content = render(lines)
    req_file = repo_root / "requirements.txt"
    existing_text = req_file.read_text(encoding="utf-8") if req_file.exists() else ""

    if parse_requirement_set(existing_text) == parse_requirement_set(content):
        sys.exit(0)

    if args.fix:
        req_file.write_text(content, encoding="utf-8")
        print(f"Updated {req_file}")
        sys.exit(0)

    print(
        f"{req_file} is out of sync with addon manifests' external_dependencies.\n"
        f"Run `solt-check-requirements --fix` to regenerate it.",
        file=sys.stderr,
    )
    sys.exit(1)


if __name__ == "__main__":
    main()
